# Generated by Django 5.2 on 2025-09-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrai', '0002_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
